version: '3.8'

services:
  db:
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4096M
        reservations:
          cpus: '1.0'
          memory: 2048M

  backend:
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4096M
        reservations:
          cpus: '1.0'
          memory: 1048M

  frontend:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M

  mlflow:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
